Group invitation system
cornell-dti/cornell-go pull request #106
Opened 2023-03-07 23:55 UTC by youssef-attia

### Summary 
Added a way to invite users to groups. The extent of the changes are just the backend. The frontend will need to add a popup to react to the invitation and depending on the reaction, the user will either join or ignore the group.

### Test Plan 

Tested directly using postman

2023-03-14 22:15 UTC, erichuang27 approved these changes

2023-03-14 22:15 UTC, erichuang27 commented on server/src/group/group.gateway.ts
> +    if (!user.administrator) return;
send a this.clientservice.emitErrorData() in the future

2023-03-14 22:15 UTC, erichuang27 commented on server/src/group/group.service.ts
> +      this.clientService.sendUpdate('groupInvitation', group.id, true, dto);
Why, explain

2023-03-27 00:16 UTC, BrianLa0616 commented
Great work! I was wondering if we should also emit an update for the user that is receiving an invitation. It might not be necessary, but I think that it'll be a good addition for anyone listening to the user.

2023-03-27 00:45 UTC, neketka requested changes
All good except the username issue.

2023-03-27 00:45 UTC, neketka commented on server/src/group/group.gateway.ts
> +    await this.groupService.emitGroupInvite(group, data.targetUsername, user);
Change data.targetUsername to user.username

2023-03-29 21:53 UTC, neketka approved these changes
LGTM

2023-03-29 21:53 UTC, merged