Challenges preview
cornell-dti/cornell-go pull request #132
Opened 2023-09-17 16:43 UTC by BrianLa0616

### Summary 

Implemented challenge preview page
Documentation: https://docs.google.com/document/d/1o5FAF4aDbH9s3s6_Xxgw5DxH_D2OONf-cTeJ7_5OHk0/edit

- [x] All designs have been implemented
- [x] fixed labels to be cleaner and more accurate

Remaining TODOs:

- [ ] Connect start challenge with backend

Depends on #{number of PR}

### Test Plan 

Use emulator to make sure everything is working

### Breaking Changes  

Home page changed to ChallengesPage

2023-09-25 14:32 UTC, neketka requested changes
See comments. It looks good overall, but you should think about ways to increase code reuse between challenges and journeys. Since we use camelCase throughout this project, make sure to use it here as well except for compile-time constants which are in SCREAMING_SNAKE_CASE.

2023-09-25 14:32 UTC, neketka commented on game/lib/main.dart
> -          home: SplashPageWidget(),
Keep this to the registration page we don't want a page to take over the master branch. I will make a way to navigate here later.

2023-09-25 14:32 UTC, neketka commented on game/lib/challenges/challenge_cell_new.dart
> +  final int challenge_points;
camelCase

2023-09-25 14:32 UTC, neketka commented on game/lib/challenges/challenge_cell_new.dart
> +  final int challenge_points;
camelCase

2023-09-25 14:32 UTC, neketka commented on game/lib/journeys/journey_cell.dart
>    final int challenge_points;
camelCase, but also think about if you can reuse the challenge cell instead of making a whole journey cell

2023-09-25 14:32 UTC, neketka commented on game/lib/journeys/journey_cell.dart
>    final int challenge_points;
camelCase

2023-10-02 02:02 UTC, tuckerstanley reviewed
Having emulator issues so not able to run this to check whether code works / formatted correctly, but it looks much better than the previous revision with the code refactoring and breaking Preview into its own component and then using it in both Journeys and Challenges. Left a nit, but looks good so far.

2023-10-04 21:21 UTC, BrianLa0616 commented on game/lib/journeys/journey_cell.dart
> +                  numberCompleted: numberCompleted,
Those arguments are optional, so I think we need to include them.

2023-10-04 21:38 UTC, neketka approved these changes
LGTM

2023-10-04 21:39 UTC, merged