Gameplay page and google maps
cornell-dti/cornell-go pull request #149
Opened 2024-02-12 03:03 UTC by cgu2020

### Summary 

This pull request is the first step towards implementing gameplay page 

- [] implemented general design
- [] connect backend to gameplay page
- [] connect challenges to navigate to their respective gameplay page
- [] google maps integration

2024-02-12 03:29 UTC, nit0107 reviewed
Nice job updating the gameplay view and adding frontend features!

2024-02-12 03:35 UTC, neketka requested changes
Looking good so far! Some minor nits in the comments.

2024-02-12 03:35 UTC, neketka commented on game/lib/gameplay/gameplay_page.dart
>  List<Widget> generate_progress(tasks, tasks_completed) {
Make sure to use camelCase when writing out variable names. Also, explicitly specify the type of the arguments so it isn't dynamic.

2024-02-12 03:35 UTC, neketka commented on game/lib/gameplay/gameplay_page.dart
>    List<Widget> progress_blocks = [];
camelCase

2024-02-12 03:35 UTC, neketka commented on game/lib/gameplay/gameplay_page.dart
>    for (var i = 0; i < tasks; i++) {
Use of tasks here is confusing, an explicit type would be helpful. Consider changing to something like taskCount.

2024-02-12 03:35 UTC, neketka commented on game/lib/gameplay/gameplay_page.dart
> +                    color: Color.fromARGB(255, 255, 255, 255),
Probably use a hex color here for easy copying from Figma.

2024-02-21 06:40 UTC, cathli66 commented
No need to deal with google maps integration! I'm handling that part, just let me know when the frontend is ready and we can merge in the PR so I can add in the map. You could make a separate PR for connecting it to the backend after

2024-03-07 02:26 UTC, cathli66 approved these changes
All the UI stuff looks good to me! I guess you must have updated or reinstalled the dependencies to change package-lock.json? Weird that it would be completely rewritten

2024-03-08 05:01 UTC, cathli66 submitted a review, later dismissed

2024-03-08 05:21 UTC, cathli66 approved these changes
The UI matches the Figma designs!

2024-03-08 05:21 UTC, merged