Completed journeys/challenges photo feed
cornell-dti/cornell-go pull request #176
Opened 2024-03-24 19:43 UTC by nit0107

### Summary 

This pull request includes the implementation of the photo feed for completed journeys/challenges on the profile page. 

- [x] implemented scrollable photo feed
- [x] implemented swipeable carousel that allows for multiple images
- [x] implemented stateful widget to use for multiple challenges
- [x] navigation from main profile page

Remaining TODOs:

- [ ] connect with backend

### Test Plan 

<img width="348" alt="image" src="https://github.com/cornell-dti/cornell-go/assets/68392119/7b4acfce-a7ea-4814-9d47-5429828f04c8">

<img width="327" alt="image" src="https://github.com/cornell-dti/cornell-go/assets/68392119/6edc89d1-da39-4af9-9c00-b010f6c4e860">

2024-03-25 00:22 UTC, neketka requested changes
Really good progress, check out some of my comments

2024-03-25 00:22 UTC, neketka commented on game/lib/preview/preview.dart
>  enum previewType { challenge, journey }
Nit: PreviewType instead of previewType

2024-03-25 00:22 UTC, neketka commented on game/lib/preview/preview.dart
>  enum previewType { challenge, journey }
Also CHALLENGE and JOURNEY

2024-03-25 00:22 UTC, neketka commented on package.json
> +  },
We already have this in the server folder and it doesn't look like you've added any scripts. Is this necessary?

2024-03-25 02:23 UTC, jasmineee-li commented
Tried out on my end -- this looks great & matches well w/the handed-off designs! Nikita catches some good things above

2024-04-10 21:33 UTC, jasmineee-li commented
checked CompletedChallengesPage() on my end after the typo fix; works for me! nice job

2024-04-10 21:40 UTC, jasmineee-li approved these changes

2024-04-11 01:35 UTC, merged