Ta375/add category
cornell-dti/cornell-go pull request #182
Opened 2024-04-09 22:38 UTC by 3TTemi

### Summary 

Updating Prisma Schema, DTO's, and Flutter models to include an events category (FOOD, NATURE, HISTORICAL, CAFE, DININGHALL, DORM)

- [x] Ithaca Commmons enum value changes as well

### Test Plan 

Regular tests to the backend to see that my changes didnt generally break anything

2024-04-17 01:38 UTC, neketka requested changes
Good job on adding categories! Make sure to look over my comments to improve your code style and readibility

2024-04-17 01:38 UTC, neketka commented on admin/src/all.dto.ts
> +type LocationTypeDto =
Major conflict between this and the other location type.

2024-04-17 01:38 UTC, neketka commented on admin/src/components/Challenges.tsx
> +        (challenge.location as string) === "ENG_QUAD"
Please refactor this into a switch case

2024-04-17 01:38 UTC, neketka commented on admin/src/components/Challenges.tsx
> +    location:
Also refactor into a switch case

2024-04-17 01:38 UTC, neketka commented on admin/src/components/Events.tsx
> +    (props.event.category as string) === "FOOD"
Also refactor into a switch case

2024-04-17 01:38 UTC, neketka commented on admin/src/components/Events.tsx
> +      (form[5] as OptionEntryForm).value === 0
Refactor into a switch case

2024-04-17 01:38 UTC, neketka commented on admin/src/components/Events.tsx
> +        (event.category as string) === "FOOD"
Refactor into a switch case

2024-04-17 01:38 UTC, neketka commented on server/src/challenge/challenge.dto.ts
> +  EngQuad = 'ENG_QUAD',
Here is where the conflict comes from, make sure to go over this and updateapi again

2024-04-17 01:38 UTC, neketka commented on server/src/challenge/challenge.e2e-spec.ts
> +        location: LocationTypeDto['EngQuad' as keyof typeof LocationTypeDto],
Not entirely sure what's happening here, but there is a high likelihood you can simplify this

2024-04-17 01:38 UTC, neketka commented on server/src/challenge/challenge.e2e-spec.ts
> +        location: LocationTypeDto['Any' as keyof typeof LocationTypeDto],
Here as well

2024-04-17 01:38 UTC, neketka commented on server/src/challenge/challenge.e2e-spec.ts
> +        location: LocationTypeDto['EngQuad' as keyof typeof LocationTypeDto],
And here

2024-04-17 01:38 UTC, neketka commented on server/src/challenge/challenge.service.ts
> +            challenge.location as String as keyof typeof LocationType
Please simplify this

2024-04-17 01:38 UTC, neketka commented on server/src/event/event.dto.ts
> +  category?: 'FOOD' | 'NATURE' | 'HISTORICAL' | 'CAFE' | 'DININGHALL' | 'DORM';
Make this into an enum instead of inlining all these possible strings

2024-04-17 01:38 UTC, neketka commented on server/src/organization/organization.e2e-spec.ts
> +      location: LocationTypeDto['ARTS_QUAD' as keyof typeof LocationTypeDto],
Simplify

2024-04-18 01:50 UTC, neketka requested changes
See comments. In general, IIFE is used for scoping, not for making your switch loops return early. It makes it very hard to understand your code while decreasing line count negligibly. Now, what you can do it make a function that takes in a category or string as a parameter separately. This would at least warrant a function and it easy to understand. All in all, it's a cool application of lambdas, but unfortunately readibility suffers.

2024-04-18 01:50 UTC, neketka commented on admin/src/components/Events.tsx
> +      options: ["FOOD", "NATURE", "HISTORICAL", "CAFE", "DININGHALL", "DORM"],
Consider making this into a constant since it seems you are writing this a lot

2024-04-18 02:42 UTC, cathli66 requested changes
If you see a lot of repetition in your code, you should try to reduce repetitive patterns and duplicate code and logic in favor of modular and referenceable code. This is called DRY - Don't Repeat Yourself!

2024-04-18 02:42 UTC, cathli66 commented on admin/src/components/Challenges.tsx
> +        "Any",
Capitalize ANY for consistency here

2024-04-18 02:42 UTC, cathli66 commented on admin/src/components/Challenges.tsx
> +      })(),
Or just move your options array outside of the object definition (as Nikita suggested) and do options.indexOf(challenge.location)

2024-04-18 02:42 UTC, cathli66 commented on admin/src/components/Challenges.tsx
> +    location: (() => {
Move your options array out and do options[form[1]]

2024-04-18 02:42 UTC, cathli66 commented on admin/src/components/Events.tsx
> +        return "Dorm";
You can just subscript the string after the first letter to set lowercase rather than this entire switch statement

2024-04-20 20:08 UTC, cathli66 approved these changes

2024-04-20 20:21 UTC, merged