Added setCurrentEvent to the group gateway and createEventTracker to the event service
cornell-dti/cornell-go pull request #30
Opened 2022-03-03 00:07 UTC by youssef-attia

### Summary 

This pull request is the first step towards implementing feature Foo

- [x] implemented setCurrentEvent and createEventTracker

### Test Plan 

### Notes 

### Blockers 

- A newly discovered dependency that hasn’t been addressed

### Breaking Changes  

- Database schema change (anything that changes TypeORM entities)
- Other change that could cause problems (Detailed in notes)

2022-03-03 04:16 UTC, cathli66 approved these changes
Looks great! Maybe there is some way to reduce code reuse in the try catch block?

2022-03-03 04:22 UTC, neketka requested changes
Please resolve the CI issues before merging.

2022-03-03 15:54 UTC, neketka requested changes

2022-03-03 15:54 UTC, neketka commented on server/src/group/group.gateway.ts
> +    private eventService: EventService,
You added EventService here, but GroupModule does not import EventModule in its 'imports' array. This code will not start if you were to run 'docker compose up'.

2022-03-10 17:59 UTC, neketka requested changes
Last few changes, but afterwards this should be ready to go!

2022-03-10 17:59 UTC, neketka commented on server/src/group/group.gateway.ts
> +          if (memberEvent.event.id != data.eventId)
I don't think this condition is necessary

2022-03-10 17:59 UTC, neketka commented on server/src/group/group.gateway.ts
> +    this.clientService.emitUpdateGroupData(user, updateGroupData);
Notify all members, not just this one.

2022-03-13 19:24 UTC, neketka approved these changes
LGTM

2022-03-13 19:26 UTC, merged