Implemented group.gateway.joinGroup, leaveGroup.
cornell-dti/cornell-go pull request #38
Opened 2022-03-08 22:19 UTC by cathli66

### Summary

This pull request implements part of GroupGateway.

- [x] implemented requestGroupData
- [x] implemented joinGroup
- [x] implemented leaveGroup

2022-03-08 22:23 UTC, cathli66 commented on server/src/group/group.service.ts
> +      throw NotFoundError
I'm not sure if throwing an error is the best here, or if there is a better way to handle possible invalid ids. Could I just assume that all id's are correct as a precondition?

2022-03-09 04:47 UTC, neketka requested changes
Left some changes for you to make. Hopefully, this clarifies things!

2022-03-09 04:47 UTC, neketka commented on server/src/group/group.gateway.ts
> +    this.requestGroupData(user, {});
Update both members of the old group and new group, not just the one person.

2022-03-09 04:47 UTC, neketka commented on server/src/group/group.gateway.ts
> +    this.requestGroupData(user, {});
Update both members of the old group and new group, not just the one person.

2022-03-09 04:47 UTC, neketka commented on server/src/group/group.gateway.ts
> +    this.groupService.joinGroup(user, data.groupId);
await on this

2022-03-09 04:47 UTC, neketka commented on server/src/group/group.gateway.ts
> +    this.groupService.leaveGroup(user);
await on this

2022-03-09 04:47 UTC, neketka commented on server/src/group/group.service.ts
> +    if (group == null) throw NotFoundError;
It would throw an exception if you do "findOneOrFail"

2022-03-09 04:47 UTC, neketka commented on server/src/group/group.service.ts
> +  async getGroupFromID(id: string): Promise<Group> {
Maybe call this "byFriendlyId", so it's not confused with the real id.

2022-03-09 04:47 UTC, neketka commented on server/src/group/group.service.ts
> +    this.joinGroup(user, newGroupId);
await on this

2022-03-09 04:47 UTC, neketka commented on server/src/group/group.service.ts
> +    this.removeUserFromGroup(user);
await on this

2022-03-09 04:47 UTC, neketka commented on server/src/group/group.service.ts
> +    this.joinGroup(user, newGroupId);
createFromEvent already joins the person into a new group as far as I'm aware

2022-03-09 04:47 UTC, neketka commented on server/src/group/group.service.ts
> +  async removeUserFromGroup(user: User) {
Consider returning Promise<Group | null> where it returns group if it still exists and null if it does not. It'll help you when you are making members of the old group (if the group exists that is) aware that someone has left.

2022-03-09 04:47 UTC, neketka commented on server/src/group/group.service.ts
> +  async joinGroup(user: User, joinId: string) {
same thing as in removeUserFromGroup, but return removeUserFromGroup's value at the end of the function

2022-03-09 04:47 UTC, neketka commented on server/src/group/group.service.ts
> +  async leaveGroup(user: User) {
Same thing as in removeUserFromGroup, but you'll have to do this some other way than joinGroup since you do not use removeUserFromGroup.

2022-03-10 18:00 UTC, neketka approved these changes
LGTM

2022-03-10 19:37 UTC, merged