Testing for Google Log In.
cornell-dti/cornell-go pull request #41
Opened 2022-03-11 23:14 UTC by nirbhaysinghnarang

Current error: call to connectGoogle() returns 'verify error'.

### Summary 

This pull request is the first step towards implementing Sign in With Google

- [ ] resolve 'verify error' bug.
- [ ] implement Z

2022-03-19 21:14 UTC, cathli66 reviewed
Great work! This helped me understand how flutter works with the backend.

2022-03-20 01:56 UTC, youssef-attia reviewed
I feel like a lot of the database connection is really specific so I don't really understand all the work with checksums and stuff. I did get an understanding of the strategy used to make sure the user has their location turned on for the app. I also found it interesting that I'm seeing some of the data properties that come up in the database being sent during the login response. The structure of a widget in Flutter really follows an object model I feel and it seems to make sense to me. Great work overall.

2022-03-20 22:50 UTC, neketka requested changes
Make sure to use the correct ApiClient when you're writing your code.

2022-03-20 22:50 UTC, neketka commented on game/lib/login/login_page.dart
> +                      final client = ApiClient(widget.storage, widget.API_URL);
You should not be creating a new ApiClient, but consuming the one at the top of the hierarchy. Use the consumer widget for that.

2022-03-20 22:50 UTC, neketka commented on game/lib/login/login_page.dart
> +    if (await ApiClient(widget.storage, widget.API_URL).tryRelog()) {
Same here, don't make a new one.

2022-03-26 15:58 UTC, neketka approved these changes
Looks complete!

2022-03-26 16:01 UTC, merged