Leaderboard data
cornell-dti/cornell-go pull request #42
Opened 2022-03-16 22:33 UTC by BrianLa0616

### Added consumer to leaderboard page.

Still has bugs.

2022-03-19 23:14 UTC, nirbhaysinghnarang requested changes
When trying to load the leaderboard screen, an exception occurs:
<img width="908" alt="Screenshot 2022-03-19 at 7 10 54 PM" src="https://user-images.githubusercontent.com/84955878/159141521-f5a78314-f650-4096-a729-07743b401884.png">

2022-03-20 22:32 UTC, neketka requested changes
Take a look at the comments I made.

2022-03-20 22:32 UTC, neketka commented on game/lib/leaderboard/leaderboard_widget.dart
> +                      leaderBoardUserCell(context, list.elementAt(i).username,
This cell actually needs to occur only once at the very top, since this is actually the current user.

2022-03-20 22:32 UTC, neketka commented on game/lib/leaderboard/leaderboard_widget.dart
> +                    for (int i = min(6, list.length); i < 6; i++)
Why a minimum of 6?

2022-03-26 17:57 UTC, neketka approved these changes
LGTM

2022-03-26 18:09 UTC, nirbhaysinghnarang approved these changes

2022-03-26 19:55 UTC, merged