Added profanity filter
cornell-dti/cornell-go pull request #55
Opened 2022-04-15 03:42 UTC by nirbhaysinghnarang

Added profanity filter to Flutter frontend.

2022-04-17 22:28 UTC, cathli66 reviewed
Although my Flutter knowledge is limited, this looks fine by me. Does the profanity filter package used take into account words that are not standalone, like "f***hi"? If not, how are you planning to implement a check for these situations?

2022-04-18 01:39 UTC, youssef-attia commented
From what I see, you are pulling an array of profanities from some API and checking the usernames to see if any of the usernames contain a profanity. I'm wondering if some limit on the ascii characters that users are able to enter for their username. I feel like if not, this may add several possibilities of bypassing the filter through alternate ascii representations but at the same time we don't want to limit user freedom too much. Otherwise, the logic of the code looks great to me. Good work.

2022-04-19 04:43 UTC, cgu2020 reviewed
Seems good. However, is it possible to just include the profanity list into the app rather than fetch the data from the url? I am not a frontend developer, but I feel like it would be easier and faster to include the txt file if possible.

2022-04-19 16:55 UTC, neketka requested changes
Check comment.

2022-04-19 16:55 UTC, neketka commented on game/ios/Runner.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = U9S73WTH2W;
Lots of weird config things that should probably not be in this PR, so I don't want to approve it just yet until we know that this won't affect our iOS build.

2022-04-29 22:29 UTC, closed without merging