Eric admin UI
cornell-dti/cornell-go pull request #7
Opened 2021-10-29 21:19 UTC by lobsterdude3

### Summary 

This pull request is the first step towards implementing the admin panel

- [x] install necessary libraries (react, material UI)
- [x] Added beginning of UI with the sidebar, and app bar.

Remaining TODOs:

- [ ] Add icons for sidebars
- [ ] Change styling

### Test Plan 

Launch code using npm start and play around with UI

### Notes 

https://gyazo.com/841ded7ad400156494048674bf6941db

screenshot of UI

2021-10-30 18:18 UTC, markd88 commented on admin/src/Sidebar.tsx
> +    >
It will be good if the code is more compact

2021-10-30 18:21 UTC, markd88 approved these changes
The code is good

2021-10-30 18:21 UTC, markd88 commented on admin/src/Sidebar.tsx
> +    >
Leave some blanks to make the code more structured

2021-10-31 16:52 UTC, neketka requested changes

2021-10-31 16:52 UTC, neketka commented on admin/src/Sidebar.tsx
> +        aria-label="Vertical tabs example"
Make sure to remove the sample code from the tutorial and name it appropriately.

2021-12-06 02:48 UTC, neketka approved these changes

2021-12-06 02:50 UTC, merged