added favorites into schema and implemented setFavorite in event.serv…
cornell-dti/cornell-go pull request #93
Opened 2023-02-10 23:59 UTC by cli66

…ice.ts

### Summary 

Keeps track of favorite events that a user marked

- [x] implemented setFavorite in event.service.ts
- [x] updated the user and event DTO
- [x] updated schema and db

Remaining TODOs:

- [ ] implement in flutter (frontend)
- [ ] test in Postman

### Notes 

- Database schema change (added favorites EventBase[] to Users and userFavorite User[] in EventBase)

2023-02-12 00:57 UTC, erichuang27 commented
Run prettier and resubmit, also should test in postman as well before merging. Looks good otherwise

2023-02-12 00:57 UTC, erichuang27 requested changes
Run prettier. Also you should test in postman as well.

2023-02-13 04:22 UTC, cgu2020 reviewed
We should also add an unfavorite gateway unless updateUserData works as an unset favorite. Otherwise, this looks good!

2023-02-21 16:24 UTC, neketka commented
> We should also add an unfavorite gateway unless updateUserData works as an unset favorite. Otherwise, this looks good!

We should not, setFavorite already takes in a bool

2023-03-14 22:09 UTC, erichuang27 approved these changes
looks good

2023-03-14 22:09 UTC, erichuang27 commented on server/src/event/event.service.ts
> +      // challengeIds: event.challengeIds,
do you still need this stuff or can it be removed

2023-03-14 22:14 UTC, merged