Added methods to manage organizations
cornell-dti/cornell-go pull request #98
Opened 2023-02-13 03:48 UTC by BrianLa0616

### Added methods to join organization and add managers to organizations.

- [x] implemented addManager and joinOrganization

Remaining TODOs:

- [ ] allow adding managers from admin page

2023-02-21 16:23 UTC, neketka requested changes

2023-02-21 16:23 UTC, neketka commented on admin/src/components/Organizations.tsx
> +    { name: "Add Manager by Email", characterLimit: 256, value: "" },
I was thinking something along the lines of another dialog box to do this.

2023-02-21 16:23 UTC, neketka commented on server/src/organization/organization.dto.ts
> +  manager_email: string;
DTO looks different here, also this does not belong here. Instead, the frontend should be calling addManager to do this

2023-02-21 16:23 UTC, neketka commented on server/src/organization/organization.gateway.ts
> +        await this.orgService.addManager(user, org_data.manager_email, org);
Don't do this logic here

2023-03-05 21:40 UTC, cli66 commented
The logic looks great to me! Would it be better to search for the manager using their user id instead of the email since the id is generated by us? Also is this fully ready to be tested in the frontend?

2023-03-24 21:02 UTC, neketka approved these changes

2023-03-24 21:03 UTC, merged